### ISSUE TITLE
插件存在错误无法加载

### ISSUE THREAD

**Issue by fengyacac** [bs-community/blessing-skin-plugins#120]
### Which version of Blessing Skin are you using?

v6.0.0-beta.3

### Which version of PHP are you using?

7.4

### What browsers are you seeing the problem on?

Chrome

### Which web server are you using?

Nginx

### What happened?

「OAuth 客户端核心」插件存在错误，无法加载。

### Error Logs

```text
[stacktrace]
#0 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(669): Illuminate\\Foundation\\Application->resolveProvider()
bs-community/blessing-skin-server#1 /www/wwwroot/skin.tgamebbs.com/plugins/oauth/bootstrap.php(8): Illuminate\\Foundation\\Application->register()
bs-community/blessing-skin-server#2 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Filesystem\\Filesystem::{closure}()
bs-community/blessing-skin-server#3 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
bs-community/blessing-skin-server#4 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure()
bs-community/blessing-skin-server#5 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
bs-community/blessing-skin-server#6 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call()
bs-community/blessing-skin-server#7 /www/wwwroot/skin.tgamebbs.com/app/Services/PluginManager.php(200): Illuminate\\Container\\Container->call()
bs-community/blessing-skin-server#8 /www/wwwroot/skin.tgamebbs.com/app/Services/PluginManager.php(139): App\\Services\\PluginManager->loadBootstrapper()
bs-community/blessing-skin-server#9 /www/wwwroot/skin.tgamebbs.com/app/Services/PluginManager.php(118): App\\Services\\PluginManager->bootPlugin()
bs-community/blessing-skin-server#10 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): App\\Services\\PluginManager->App\\Services\\{closure}()
bs-community/blessing-skin-server#11 /www/wwwroot/skin.tgamebbs.com/app/Services/PluginManager.php(118): Illuminate\\Support\\Collection->each()
bs-community/blessing-skin-server#12 /www/wwwroot/skin.tgamebbs.com/app/Providers/PluginServiceProvider.php(18): App\\Services\\PluginManager->boot()
bs-community/blessing-skin-server#13 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\PluginServiceProvider->boot()
bs-community/blessing-skin-server#14 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
bs-community/blessing-skin-server#15 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
bs-community/blessing-skin-server#16 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
bs-community/blessing-skin-server#17 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call()
bs-community/blessing-skin-server#18 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(914): Illuminate\\Container\\Container->call()
bs-community/blessing-skin-server#19 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(895): Illuminate\\Foundation\\Application->bootProvider()
bs-community/blessing-skin-server#20 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
bs-community/blessing-skin-server#21 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(896): array_walk()
bs-community/blessing-skin-server#22 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
bs-community/blessing-skin-server#23 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
bs-community/blessing-skin-server#24 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\\Foundation\\Application->bootstrapWith()
bs-community/blessing-skin-server#25 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(136): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
bs-community/blessing-skin-server#26 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
bs-community/blessing-skin-server#27 /www/wwwroot/skin.tgamebbs.com/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
bs-community/blessing-skin-server#28 {main}
"} 
[2021-08-19 02:03:45] production.ERROR: Class 'SocialiteProviders\Manager\ServiceProvider' not found {"exception":"[object] (Error(code: 0): Class 'SocialiteProviders\\Manager\\ServiceProvider' not found at /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:735)
[stacktrace]
#0 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(669): Illuminate\\Foundation\\Application->resolveProvider()
bs-community/blessing-skin-server#1 /www/wwwroot/skin.tgamebbs.com/plugins/oauth/bootstrap.php(8): Illuminate\\Foundation\\Application->register()
bs-community/blessing-skin-server#2 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Filesystem\\Filesystem::{closure}()
bs-community/blessing-skin-server#3 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
bs-community/blessing-skin-server#4 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure()
bs-community/blessing-skin-server#5 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
bs-community/blessing-skin-server#6 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call()
bs-community/blessing-skin-server#7 /www/wwwroot/skin.tgamebbs.com/app/Services/PluginManager.php(200): Illuminate\\Container\\Container->call()
bs-community/blessing-skin-server#8 /www/wwwroot/skin.tgamebbs.com/app/Services/PluginManager.php(139): App\\Services\\PluginManager->loadBootstrapper()
bs-community/blessing-skin-server#9 /www/wwwroot/skin.tgamebbs.com/app/Services/PluginManager.php(118): App\\Services\\PluginManager->bootPlugin()
bs-community/blessing-skin-server#10 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): App\\Services\\PluginManager->App\\Services\\{closure}()
bs-community/blessing-skin-server#11 /www/wwwroot/skin.tgamebbs.com/app/Services/PluginManager.php(118): Illuminate\\Support\\Collection->each()
bs-community/blessing-skin-server#12 /www/wwwroot/skin.tgamebbs.com/app/Providers/PluginServiceProvider.php(18): App\\Services\\PluginManager->boot()
bs-community/blessing-skin-server#13 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\PluginServiceProvider->boot()
bs-community/blessing-skin-server#14 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
bs-community/blessing-skin-server#15 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
bs-community/blessing-skin-server#16 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
bs-community/blessing-skin-server#17 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call()
bs-community/blessing-skin-server#18 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(914): Illuminate\\Container\\Container->call()
bs-community/blessing-skin-server#19 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(895): Illuminate\\Foundation\\Application->bootProvider()
bs-community/blessing-skin-server#20 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
bs-community/blessing-skin-server#21 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(896): array_walk()
bs-community/blessing-skin-server#22 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
bs-community/blessing-skin-server#23 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
bs-community/blessing-skin-server#24 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\\Foundation\\Application->bootstrapWith()
bs-community/blessing-skin-server#25 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(136): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
bs-community/blessing-skin-server#26 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
bs-community/blessing-skin-server#27 /www/wwwroot/skin.tgamebbs.com/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
bs-community/blessing-skin-server#28 {main}
"} 
[2021-08-19 02:04:31] production.ERROR: Class 'SocialiteProviders\Manager\ServiceProvider' not found {"exception":"[object] (Error(code: 0): Class 'SocialiteProviders\\Manager\\ServiceProvider' not found at /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:735)
[stacktrace]
#0 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(669): Illuminate\\Foundation\\Application->resolveProvider()
bs-community/blessing-skin-server#1 /www/wwwroot/skin.tgamebbs.com/plugins/oauth/bootstrap.php(8): Illuminate\\Foundation\\Application->register()
bs-community/blessing-skin-server#2 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Filesystem\\Filesystem::{closure}()
bs-community/blessing-skin-server#3 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
bs-community/blessing-skin-server#4 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure()
bs-community/blessing-skin-server#5 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
bs-community/blessing-skin-server#6 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call()
bs-community/blessing-skin-server#7 /www/wwwroot/skin.tgamebbs.com/app/Services/PluginManager.php(200): Illuminate\\Container\\Container->call()
bs-community/blessing-skin-server#8 /www/wwwroot/skin.tgamebbs.com/app/Services/PluginManager.php(139): App\\Services\\PluginManager->loadBootstrapper()
bs-community/blessing-skin-server#9 /www/wwwroot/skin.tgamebbs.com/app/Services/PluginManager.php(118): App\\Services\\PluginManager->bootPlugin()
bs-community/blessing-skin-server#10 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): App\\Services\\PluginManager->App\\Services\\{closure}()
bs-community/blessing-skin-server#11 /www/wwwroot/skin.tgamebbs.com/app/Services/PluginManager.php(118): Illuminate\\Support\\Collection->each()
bs-community/blessing-skin-server#12 /www/wwwroot/skin.tgamebbs.com/app/Providers/PluginServiceProvider.php(18): App\\Services\\PluginManager->boot()
bs-community/blessing-skin-server#13 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\PluginServiceProvider->boot()
bs-community/blessing-skin-server#14 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
bs-community/blessing-skin-server#15 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
bs-community/blessing-skin-server#16 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
bs-community/blessing-skin-server#17 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call()
bs-community/blessing-skin-server#18 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(914): Illuminate\\Container\\Container->call()
bs-community/blessing-skin-server#19 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(895): Illuminate\\Foundation\\Application->bootProvider()
bs-community/blessing-skin-server#20 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
bs-community/blessing-skin-server#21 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(896): array_walk()
bs-community/blessing-skin-server#22 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
bs-community/blessing-skin-server#23 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
bs-community/blessing-skin-server#24 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\\Foundation\\Application->bootstrapWith()
bs-community/blessing-skin-server#25 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(136): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
bs-community/blessing-skin-server#26 /www/wwwroot/skin.tgamebbs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
bs-community/blessing-skin-server#27 /www/wwwroot/skin.tgamebbs.com/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
bs-community/blessing-skin-server#28 {main}
"}
```

### Steps to Reproduce

插件存在错误。无法加载

**Comment by g-plane** [comment]
插件的问题请在 blessing-skin-plugins 仓库提 issue。

**Comment by mochaaP** [comment]
同。

![Screenshot_20220617182954](https://user-images.githubusercontent.com/21154023/174286440-869c2de3-1935-4a33-81b6-b9131143da22.png)

疑似構建時 composer 依賴拉取邏輯有問題。

**Comment by mochaaP** [comment]
我这个是缺了 `php-intl`，Alpine 用户需要注意。
