### ISSUE TITLE
「OAuth 客户端核心」插件存在错误，无法加载。

### ISSUE THREAD

**Issue by Jerry12228** [bs-community/blessing-skin-plugins#164]
安装「OAuth 客户端核心」插件, 刷新页面提示「OAuth 客户端核心」插件存在错误，无法加载。
开debug, 报错:
Class "SocialiteProviders\Manager\ServiceProvider" not found 

php版本8.1

**Comment by Jerry12228** [comment]
日志::

```
[2022-10-09 22:15:28] production.ERROR: Class "SocialiteProviders\Manager\ServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"SocialiteProviders\\Manager\\ServiceProvider\" not found at /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:745)
[stacktrace]
#0 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(679): Illuminate\\Foundation\\Application->resolveProvider()
#1 /www/wwwroot/account.mc.jerrybest.tk/plugins/oauth/bootstrap.php(8): Illuminate\\Foundation\\Application->register()
#2 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Filesystem\\Filesystem::{closure}()
#3 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#7 /www/wwwroot/account.mc.jerrybest.tk/app/Services/PluginManager.php(200): Illuminate\\Container\\Container->call()
#8 /www/wwwroot/account.mc.jerrybest.tk/app/Services/PluginManager.php(139): App\\Services\\PluginManager->loadBootstrapper()
#9 /www/wwwroot/account.mc.jerrybest.tk/app/Services/PluginManager.php(118): App\\Services\\PluginManager->bootPlugin()
#10 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): App\\Services\\PluginManager->App\\Services\\{closure}()
#11 /www/wwwroot/account.mc.jerrybest.tk/app/Services/PluginManager.php(118): Illuminate\\Support\\Collection->each()
#12 /www/wwwroot/account.mc.jerrybest.tk/app/Providers/PluginServiceProvider.php(18): App\\Services\\PluginManager->boot()
#13 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\PluginServiceProvider->boot()
#14 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#18 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(924): Illuminate\\Container\\Container->call()
#19 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(905): Illuminate\\Foundation\\Application->bootProvider()
#20 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#21 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(906): array_walk()
#22 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#23 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#24 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(153): Illuminate\\Foundation\\Application->bootstrapWith()
#25 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(137): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#26 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#27 /www/wwwroot/account.mc.jerrybest.tk/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
#28 {main}
"} 
[2022-10-09 22:15:28] production.ERROR: Class "SocialiteProviders\Manager\ServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"SocialiteProviders\\Manager\\ServiceProvider\" not found at /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:745)
[stacktrace]
#0 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(679): Illuminate\\Foundation\\Application->resolveProvider()
#1 /www/wwwroot/account.mc.jerrybest.tk/plugins/oauth/bootstrap.php(8): Illuminate\\Foundation\\Application->register()
#2 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Filesystem\\Filesystem::{closure}()
#3 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#7 /www/wwwroot/account.mc.jerrybest.tk/app/Services/PluginManager.php(200): Illuminate\\Container\\Container->call()
#8 /www/wwwroot/account.mc.jerrybest.tk/app/Services/PluginManager.php(139): App\\Services\\PluginManager->loadBootstrapper()
#9 /www/wwwroot/account.mc.jerrybest.tk/app/Services/PluginManager.php(118): App\\Services\\PluginManager->bootPlugin()
#10 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): App\\Services\\PluginManager->App\\Services\\{closure}()
#11 /www/wwwroot/account.mc.jerrybest.tk/app/Services/PluginManager.php(118): Illuminate\\Support\\Collection->each()
#12 /www/wwwroot/account.mc.jerrybest.tk/app/Providers/PluginServiceProvider.php(18): App\\Services\\PluginManager->boot()
#13 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\PluginServiceProvider->boot()
#14 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#18 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(924): Illuminate\\Container\\Container->call()
#19 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(905): Illuminate\\Foundation\\Application->bootProvider()
#20 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#21 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(906): array_walk()
#22 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#23 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#24 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(153): Illuminate\\Foundation\\Application->bootstrapWith()
#25 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(137): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#26 /www/wwwroot/account.mc.jerrybest.tk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#27 /www/wwwroot/account.mc.jerrybest.tk/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
#28 {main}
"} 
```

**Comment by Linecom-lik** [comment]
从插件市场安装就不会报错了

**Comment by Jerry12228** [comment]
> 从插件市场安装就不会报错了

确实是从插件市场安装的
换了台服务器合适了
