### ISSUE TITLE
OAuth与最新开发版不兼容

### ISSUE THREAD

**Issue by LittleChest** [bs-community/blessing-skin-plugins#195]
### Blessing Skin 版本

https://github.com/bs-community/blessing-skin-server/commit/46cccdb708aa141ecce7ca34967da7b79140ad91

### PHP 版本

8.1

### 出现问题时所使用的浏览器

Chrome

### 您正在使用的 Web Server

Apache

### 您正在使用宝塔吗？

- [X] 是

### 出现了什么问题？

在最新开发版中安装OAuth后刷新就会出现这个
![image](https://github.com/bs-community/blessing-skin-server/assets/81231195/35e29fb8-4d87-469a-9f4b-a4812722cf77)

### 错误日志

```text
[2023-05-28 18:24:15] production.ERROR: require(/www/wwwroot/Skin/plugins/oauth/vendor/composer/../guzzlehttp/promises/src/functions_include.php): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): require(/www/wwwroot/Skin/plugins/oauth/vendor/composer/../guzzlehttp/promises/src/functions_include.php): Failed to open stream: No such file or directory at /www/wwwroot/Skin/plugins/oauth/vendor/composer/autoload_real.php:71)
[stacktrace]
#0 /www/wwwroot/Skin/plugins/oauth/vendor/composer/autoload_real.php(71): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
bs-community/blessing-skin-server#1 /www/wwwroot/Skin/plugins/oauth/vendor/composer/autoload_real.php(71): require()
bs-community/blessing-skin-server#2 /www/wwwroot/Skin/plugins/oauth/vendor/composer/autoload_real.php(61): composerRequirea8da9aa474ea7ba9f818d455d118162d()
bs-community/blessing-skin-server#3 /www/wwwroot/Skin/plugins/oauth/vendor/autoload.php(7): ComposerAutoloaderInita8da9aa474ea7ba9f818d455d118162d::getLoader()
bs-community/blessing-skin-server#4 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('...')
bs-community/blessing-skin-server#5 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
bs-community/blessing-skin-server#6 /www/wwwroot/Skin/app/Services/PluginManager.php(160): Illuminate\\Filesystem\\Filesystem->getRequire()
bs-community/blessing-skin-server#7 /www/wwwroot/Skin/app/Services/PluginManager.php(130): App\\Services\\PluginManager->loadVendor()
bs-community/blessing-skin-server#8 /www/wwwroot/Skin/app/Services/PluginManager.php(116): App\\Services\\PluginManager->registerPlugin()
bs-community/blessing-skin-server#9 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(245): App\\Services\\PluginManager->App\\Services\\{closure}()
bs-community/blessing-skin-server#10 /www/wwwroot/Skin/app/Services/PluginManager.php(116): Illuminate\\Support\\Collection->each()
bs-community/blessing-skin-server#11 /www/wwwroot/Skin/app/Providers/PluginServiceProvider.php(18): App\\Services\\PluginManager->boot()
bs-community/blessing-skin-server#12 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\PluginServiceProvider->boot()
bs-community/blessing-skin-server#13 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
bs-community/blessing-skin-server#14 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
bs-community/blessing-skin-server#15 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
bs-community/blessing-skin-server#16 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
bs-community/blessing-skin-server#17 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(924): Illuminate\\Container\\Container->call()
bs-community/blessing-skin-server#18 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(905): Illuminate\\Foundation\\Application->bootProvider()
bs-community/blessing-skin-server#19 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
bs-community/blessing-skin-server#20 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(906): array_walk()
bs-community/blessing-skin-server#21 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
bs-community/blessing-skin-server#22 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
bs-community/blessing-skin-server#23 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(153): Illuminate\\Foundation\\Application->bootstrapWith()
bs-community/blessing-skin-server#24 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(137): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
bs-community/blessing-skin-server#25 /www/wwwroot/Skin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
bs-community/blessing-skin-server#26 /www/wwwroot/Skin/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
bs-community/blessing-skin-server#27 {main}
"}
```

### 重现步骤

1. 下载最新预构建快照
2. 覆盖现有的Blessing Skin（或者自己建一个）
3. 去插件市场装OAuth插件
4. 刷新页面或打开任意页面

**Comment by zhinaijiang32** [comment]
我也一样但是预构都是最新的OAuth插件还是不能正常使用

**Comment by tnqzh123** [comment]
尝试一下，把 oauth 插件目录（`plugins/oauth`）下 `composer.json` 的内容改成下面这样：

```json
{
    "require": {
        "socialiteproviders/manager": "^4.0",
        "psr/log": "^3",
        "illuminate/filesystem": "^10"
    }
}
```

然后删掉 oauth 插件目录下的 `vendor` 目录和 `composer.lock` 文件（如果有），再 `composer install`。

看看这样能不能解决这个问题？

**Comment by creeperCN** [comment]
> 尝试一下，把 oauth 插件目录（）下 的内容改成下面这样：`plugins/oauth``composer.json`
> 
> {
>     "require": {
>         "socialiteproviders/manager": "^4.0",
>         "psr/log": "^3",
>         "illuminate/filesystem": "^10"
>     }
> }
> 然后删掉 oauth 插件目录下的 目录和 文件（如果有），再 。`vendor``composer.lock``composer install`
> 
> 看看这样能不能解决这个问题？

我也遇到了相同的问题 但是我没有在plugins/oauth 找到Composer.json文件 附件为日志

[laravel-2025-07-11.log](https://github.com/user-attachments/files/21172888/laravel-2025-07-11.log)

**Comment by creeperCN** [comment]
> 没有 composer.json 就自己创建。

感谢你的帮助 问题已被解决 但是在安装oauth-microsoft-live时出现500报错

**Comment by creeperCN** [comment]
没有找到composer.json

在 2025-07-19 03:07:52，"Steven Qiu" ***@***.***> 写道：

tnqzh123 left a comment (bs-community/blessing-skin-plugins#195)

同样的解决方案，在 oauth-microsoft-live 插件的 composer.json 里把任意一个 illuminate/* 的包的版本固定在 10.x，psr/log 的版本固定在 4.x，然后删除 vendor 重新 composer install。

**Comment by creeperCN** [comment]
> 同样的解决方案，在 插件的 里把任意一个 的包的版本固定在 10.x， 的版本固定在 4.x，然后删除 vendor 重新 。`oauth-microsoft-live``illuminate/*``psr/log``composer install`

您能提供一下composer.json这个文件吗 我在插件目录没有找到

**Comment by tnqzh123** [comment]
https://github.com/bs-community/blessing-skin-plugins/blob/master/plugins/oauth-microsoft-live/composer.json

**Comment by tnqzh123** [comment]
> 同样的解决方案，在 `oauth-microsoft-live` 插件的 composer.json 里把任意一个 `illuminate/*` 的包的版本固定在 10.x，`psr/log` 的版本固定在 3.x，然后删除 vendor 重新 `composer install`。

**Comment by tnqzh123** [comment]
https://github.com/bs-community/blessing-skin-plugins/issues/195#issuecomment-2997741962

解决方案证实有效，closing issue.
