### ISSUE TITLE
通过任一 OAuth 方法登陆皮肤站均返回 500 Internal Server Error

### ISSUE THREAD

**Issue by MisaLiu** [bs-community/blessing-skin-plugins#209]
以 `oauth-littleskin` 为例，配置好应用后选择「LittleSkin」登陆，在 LittleSkin 侧授权后服务器会返回错误 `500 Internal Server Error`，同时服务器有如下错误日志：

```
[2024-01-18 02:09:45] production.ERROR: Client error: `POST https://mcskin.littleservice.cn/oauth/token` resulted in a `405 Method Not Allowed` response:
{
    "message": "The GET method is not supported for route oauth/token. Supported methods: POST.",
    "exception": tru (truncated...)
 {"exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 405): Client error: `POST https://mcskin.littleservice.cn/oauth/token` resulted in a `405 Method Not Allowed` response:
{
    \"message\": \"The GET method is not supported for route oauth/token. Supported methods: POST.\",
    \"exception\": tru (truncated...)
 at /www/wwwroot/mcskin.misaliu.top/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
[stacktrace]
#0 /www/wwwroot/mcskin.misaliu.top/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\\Exception\\RequestException::create()
#1 /www/wwwroot/mcskin.misaliu.top/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#2 /www/wwwroot/mcskin.misaliu.top/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\\Promise\\Promise::callHandler()
#3 /www/wwwroot/mcskin.misaliu.top/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()
#4 /www/wwwroot/mcskin.misaliu.top/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\\Promise\\TaskQueue->run()
#5 /www/wwwroot/mcskin.misaliu.top/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#6 /www/wwwroot/mcskin.misaliu.top/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()
#7 /www/wwwroot/mcskin.misaliu.top/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#8 /www/wwwroot/mcskin.misaliu.top/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#9 /www/wwwroot/mcskin.misaliu.top/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\\Promise\\Promise->wait()
#10 /www/wwwroot/mcskin.misaliu.top/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\\Client->request()
#11 /www/wwwroot/mcskin.misaliu.top/plugins/oauth-littleskin/vendor/laravel/socialite/src/Two/AbstractProvider.php(290): GuzzleHttp\\Client->post()
#12 /www/wwwroot/mcskin.misaliu.top/plugins/oauth-littleskin/vendor/socialiteproviders/manager/src/OAuth2/AbstractProvider.php(52): Laravel\\Socialite\\Two\\AbstractProvider->getAccessTokenResponse()
#13 /www/wwwroot/mcskin.misaliu.top/plugins/oauth/src/AuthController.php(23): SocialiteProviders\\Manager\\OAuth2\\AbstractProvider->user()
#14 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Blessing\\OAuthCore\\AuthController->callback()
#15 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#16 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#17 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#18 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#19 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#20 /www/wwwroot/mcskin.misaliu.top/app/Http/Middleware/RedirectIfAuthenticated.php(11): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RedirectIfAuthenticated->handle()
#22 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#24 /www/wwwroot/mcskin.misaliu.top/app/Http/Middleware/RedirectToSetup.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RedirectToSetup->handle()
#26 /www/wwwroot/mcskin.misaliu.top/app/Http/Middleware/EnforceEverGreen.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\EnforceEverGreen->handle()
#28 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#30 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#32 /www/wwwroot/mcskin.misaliu.top/plugins/oauth-littleskin/vendor/illuminate/session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /www/wwwroot/mcskin.misaliu.top/plugins/oauth-littleskin/vendor/illuminate/session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#34 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#35 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#37 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#39 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#41 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#42 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#43 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#44 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#45 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#46 /www/wwwroot/mcskin.misaliu.top/plugins/yggdrasil-api/src/Middleware/AddApiIndicationHeader.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Yggdrasil\\Middleware\\AddApiIndicationHeader->handle()
#48 /www/wwwroot/mcskin.misaliu.top/app/Http/Middleware/DetectLanguagePrefer.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\DetectLanguagePrefer->handle()
#50 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#52 /www/wwwroot/mcskin.misaliu.top/app/Http/Middleware/ConvertEmptyStringsToNull.php(23): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#53 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#54 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#56 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#57 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#59 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#61 /www/wwwroot/mcskin.misaliu.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#62 /www/wwwroot/mcskin.misaliu.top/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
#63 {main}
"} 
```

其他的 OAuth 插件同样也会导致 500 Internal Server Error 并且无法正常使用（测试了 Microsoft Live）。

https://flareapp.io/share/NPGR8Dvm

**Comment by 2b2tplayer** [comment]
解决了吗，我也是
